name: MSVC 2019

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build-and-test:
    runs-on: windows-2019

    strategy:
      matrix:
        config: [Debug, Release]

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      working-directory: ${{runner.workspace}}
      run: |
        git clone https://github.com/Microsoft/vcpkg.git 
        cd vcpkg
        bootstrap-vcpkg.bat
        vcpkg install qt5
        vcpkg install boost-core
        vcpkg install boost-function-types 
        vcpkg install boost-geometry
        vcpkg install boost-hana
        vcpkg install boost-math
        vcpkg install boost-program-options
        vcpkg install boost-qvm
        vcpkg install boost-range
        vcpkg install boost-ublas
        vcpkg install catch2
        vcpkg install tinyxml
        vcpkg install sqlite3
        vcpkg install llvm[enable-rtti] --recurse

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.config}} -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE\vcpkg\scripts\buildsystems\vcpkg.cmake

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --config ${{matrix.config}} -j4

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ctest --build-config ${{matrix.config}}
